name 'pdqdeploy'
maintainer 'Garrett Yamada'
maintainer_email 'me@garrettyamada.com'
license 'All Rights Reserved'
description 'Installs/Configures PDQ Deploy'
long_description 'Installs PDQ Deploy console in client mode and configures a connection to a PDQ Deploy Central Server.'
version '1.0.0'
chef_version '>= 13.0'
depends 'chocolatey'
